import React, { FC, ReactElement } from "react";
import Head from "next/head";
import { ToastProvider } from "@/components/elements/ToastProvider";
import { Box, Button, styled, Typography } from "@mui/material";
import { NextPageWithLayout } from "./_app";
import { useRouter } from "next/router";

const Home: NextPageWithLayout = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Toast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledBox>
        <Typography variant="h3">Home Page</Typography>
        <Button variant="contained" onClick={() => router.push("/post")}>
          Post Page
        </Button>
        <Button variant="contained" onClick={() => router.push("/todo")}>
          Todo Page
        </Button>
      </StyledBox>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <ToastProvider>{page}</ToastProvider>;
};

export default Home;

const StyledBox = styled(Box)(
  () => `
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 80px;
    margin-top: 100px;
    flex-direction: column;
  `
);
